server:
  port: 8000

spring:
  application:
    name: 'post-service'
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

# eureka:
#   client:
#     service-url:
#       defaultZone: ${EUREKA_URI:http://localhost:8083/eureka}

# validationServer: ${VALIDATION:http://localhost:8084/users/validation}

management:
  endpoints:
    web:
      exposure:
        include: "*"
